DROP TABLE IF EXISTS requests;
CREATE TABLE requests (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    method VARCHAR(8) NOT NULL,
    url VARCHAR(255) NOT NULL,
    headers TEXT DEFAULT NULL,
    body TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ran_at TIMESTAMP DEFAULT NULL,
    finished_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX requests_method ON requests (method);

DROP TABLE IF EXISTS responses;
CREATE TABLE responses (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    request_id INTEGER REFERENCES requests(id),
    code INTEGER NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
