DROP TABLE IF EXISTS requests;
CREATE TABLE requests (
   url VARCHAR(255) NOT NULL,
   method VARCHAR(8) NOT NULL,
   code INTEGER NOT NULL DEFAULT 0,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
